spring:
  application:
    name: blog-mvc
  datasource:
    password: 12345
    username: postgres
    url: jdbc:postgresql://localhost:5432/blogposts
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
